version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "@types/node"
        versions: ["25.x"]
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
      types:
        patterns:
          - "@types/*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "node"
        versions: ["25.x"]
      - dependency-name: "@types/node"
        versions: ["25.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"