// Generates web/src/styles/tokens.css from DESIGN.md's front matter.
//
//   pnpm tokens          write the file
//   pnpm tokens:check    compare the file with DESIGN.md and write nothing
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { isMap, readDesignMd } from "./design-md.ts";

export const tokensCssPath = fileURLToPath(
  new URL("../src/styles/tokens.css", import.meta.url),
);

export function main(args: string[]): number {
  const css = buildTokensCss(readDesignMd().frontMatter);

  if (!args.includes("--check")) {
    writeFileSync(tokensCssPath, css);
    return 0;
  }

  if (readIfExists(tokensCssPath) === css) return 0;
  console.error(
    "web/src/styles/tokens.css does not match DESIGN.md. Run `pnpm tokens` in web/ to regenerate it.",
  );
  return 1;
}

// Returns the text of tokens.css: one custom property per primitive token,
// in DESIGN.md's order, grouped by where each token sits in the front matter.
export function buildTokensCss(frontMatter: Record<string, unknown>): string {
  const prefix = String(extensionOf(frontMatter)["css-prefix"]);
  const lines = [
    "/* Generated from DESIGN.md by `pnpm tokens`. Do not edit this file:",
    "   change DESIGN.md, then run `pnpm tokens` in web/. */",
    ":root {",
  ];

  for (const group of primitiveGroups(frontMatter)) {
    if (lines.length > 3) lines.push("");
    lines.push(`  /* ${group.path} */`);
    for (const [key, value] of Object.entries(group.tokens)) {
      lines.push(`  --${prefix}-${key}: ${String(value)};`);
    }
  }

  lines.push("}", "");
  return lines.join("\n");
}

interface TokenGroup {
  // Where the group sits in the front matter, such as `colors` or
  // `x-sidereal.font-size`.
  path: string;
  tokens: Record<string, unknown>;
}

// The specification's own primitive groups.
const specGroups = ["colors", "rounded", "spacing"];

// Keys under x-sidereal that hold settings, not primitive tokens.
const extensionSettings = ["css-prefix", "semantic"];

function primitiveGroups(frontMatter: Record<string, unknown>): TokenGroup[] {
  const groups: TokenGroup[] = [];
  for (const path of specGroups) {
    const tokens = frontMatter[path];
    if (isMap(tokens)) groups.push({ path, tokens });
  }
  for (const [name, tokens] of Object.entries(extensionOf(frontMatter))) {
    if (extensionSettings.includes(name) || !isMap(tokens)) continue;
    groups.push({ path: `x-sidereal.${name}`, tokens });
  }
  return groups;
}

function extensionOf(
  frontMatter: Record<string, unknown>,
): Record<string, unknown> {
  const extension = frontMatter["x-sidereal"];
  return isMap(extension) ? extension : {};
}

function readIfExists(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

// Runs main() when Node runs this file directly. It sits last, so every
// constant above is initialized before main() reads it.
if (import.meta.main) {
  process.exitCode = main(process.argv.slice(2));
}
