// Generates web/src/styles/tokens.css from DESIGN.md's front matter.
//
//   pnpm tokens          write the file
//   pnpm tokens:check    compare the file with DESIGN.md and write nothing
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { isMap, readDesignMd } from "./design-md.ts";

export const tokensCssPath = fileURLToPath(
  new URL("../src/styles/tokens.css", import.meta.url),
);

export function main(args: string[]): number {
  let css: string;
  try {
    css = buildTokensCss(readDesignMd().frontMatter);
  } catch (error) {
    if (!(error instanceof TokenError)) throw error;
    console.error(error.message);
    return 1;
  }

  if (!args.includes("--check")) {
    writeFileSync(tokensCssPath, css);
    return 0;
  }

  if (readIfExists(tokensCssPath) === css) return 0;
  console.error(
    "web/src/styles/tokens.css does not match DESIGN.md. Run `pnpm tokens` in web/ to regenerate it.",
  );
  return 1;
}

// Returns the text of tokens.css: one custom property per primitive token,
// in DESIGN.md's order, grouped by where each token sits in the front matter.
// Throws a TokenError that names every token it cannot write safely.
export function buildTokensCss(frontMatter: Record<string, unknown>): string {
  const problems = findProblems(frontMatter);
  if (problems.length > 0) {
    throw new TokenError(
      [
        "DESIGN.md holds tokens that tokens.css cannot hold:",
        ...problems.map((problem) => `  - ${problem}`),
      ].join("\n"),
    );
  }

  const prefix = String(extensionOf(frontMatter)["css-prefix"]);
  const lines = [
    "/* Generated from DESIGN.md by `pnpm tokens`. Do not edit this file:",
    "   change DESIGN.md, then run `pnpm tokens` in web/. */",
    ":root {",
  ];

  for (const group of primitiveGroups(frontMatter)) {
    if (lines.length > 3) lines.push("");
    lines.push(`  /* ${group.path} */`);
    for (const [key, value] of Object.entries(group.tokens)) {
      lines.push(`  --${prefix}-${key}: ${String(value)};`);
    }
  }

  lines.push("}", "");
  return lines.join("\n");
}

interface TokenGroup {
  // Where the group sits in the front matter, such as `colors` or
  // `x-sidereal.font-size`.
  path: string;
  tokens: Record<string, unknown>;
}

export class TokenError extends Error {}

// Lists every reason the generator cannot write DESIGN.md's tokens. An empty
// list means every token can be written.
function findProblems(frontMatter: Record<string, unknown>): string[] {
  const problems: string[] = [];
  const extension = extensionOf(frontMatter);

  if (!/^[a-z]+$/.test(String(extension["css-prefix"]))) {
    problems.push(
      "x-sidereal.css-prefix must hold lowercase letters only, such as `sr`",
    );
  }

  // Semantic and component tokens hold references, such as
  // `{colors.violet-600}`, which the generator cannot resolve yet.
  const unresolved = [
    { path: "x-sidereal.semantic", tokens: extension.semantic },
    { path: "components", tokens: frontMatter.components },
  ];
  for (const { path, tokens } of unresolved) {
    if (!isMap(tokens)) continue;
    for (const key of Object.keys(tokens)) {
      problems.push(
        `${key} (in ${path}): the generator cannot resolve references yet. Add reference lookup to web/scripts/tokens.ts in the same pull request.`,
      );
    }
  }

  for (const [name, tokens] of Object.entries(extension)) {
    if (extensionSettings.includes(name)) continue;
    const path = `x-sidereal.${name}`;
    if (!(path in valueForms)) {
      problems.push(
        `${path} has no known value form. Add one to valueForms in web/scripts/tokens.ts.`,
      );
    } else if (!isMap(tokens)) {
      problems.push(`${path} must be a map of tokens`);
    }
  }

  const firstGroupOf = new Map<string, string>();
  for (const group of primitiveGroups(frontMatter)) {
    const form = valueForms[group.path];
    for (const [key, value] of Object.entries(group.tokens)) {
      const where = `${JSON.stringify(key)} (in ${group.path})`;
      const firstGroup = firstGroupOf.get(key);
      if (firstGroup !== undefined) {
        problems.push(`${where} is also a key in ${firstGroup}`);
      }
      firstGroupOf.set(key, group.path);

      if (!/^[a-z0-9-]+$/.test(key)) {
        problems.push(
          `${where}: a key may hold only lowercase letters, digits, and hyphens`,
        );
      }
      if (refusedText.test(String(value))) {
        problems.push(
          `${where}: a value may not hold a line break, ;, {, }, <, \\, or url(, because it could end its CSS property`,
        );
      } else if (form && !form.fits(value)) {
        problems.push(`${where}: the value must be ${form.description}`);
      }
    }
  }

  return problems;
}

// Text that could end a custom property or load a file from another site.
const refusedText = /[\n\r;{}<\\]|url\(/i;

interface ValueForm {
  // Read as "the value must be <description>".
  description: string;
  fits(value: unknown): boolean;
}

const hexColor: ValueForm = {
  description: "a hex color: # and 6 hex digits, such as #0B0A0F",
  fits: (value) => typeof value === "string" && /^#[0-9A-Fa-f]{6}$/.test(value),
};

const wholePixels: ValueForm = {
  description: "a whole number of pixels, such as 14px",
  fits: (value) => typeof value === "string" && /^\d+px$/.test(value),
};

const ems: ValueForm = {
  description:
    "a decimal number of em, which may be negative, such as -0.015em",
  fits: (value) =>
    typeof value === "string" && /^-?(\d+(\.\d+)?|\.\d+)em$/.test(value),
};

const fraction: ValueForm = {
  description: "a number from 0 to 1, such as 0.45",
  fits: (value) => typeof value === "number" && value >= 0 && value <= 1,
};

const fontWeight: ValueForm = {
  description: "a whole number from 1 to 1000, such as 600",
  fits: (value) =>
    typeof value === "number" &&
    Number.isInteger(value) &&
    value >= 1 &&
    value <= 1000,
};

// Each item is a name in double quotes, or words that each start with a
// letter or a hyphen: `Inter, -apple-system, "Segoe UI", sans-serif`.
const fontFamily: ValueForm = {
  description:
    'a comma-separated font list, where each item is a name in double quotes or plain words, such as Inter, "Segoe UI", sans-serif',
  fits: (value) =>
    typeof value === "string" &&
    value
      .split(",")
      .every((item) =>
        /^("[^"]+"|[A-Za-z-][\w-]*( [A-Za-z-][\w-]*)*)$/.test(item.trim()),
      ),
};

// The form each primitive group's values must take. An x-sidereal group that
// is missing here is refused, so a new group must add its form first.
const valueForms: Record<string, ValueForm | undefined> = {
  colors: hexColor,
  rounded: wholePixels,
  spacing: wholePixels,
  "x-sidereal.font-family": fontFamily,
  "x-sidereal.font-weight": fontWeight,
  "x-sidereal.font-size": wholePixels,
  "x-sidereal.line-height": wholePixels,
  "x-sidereal.letter-spacing": ems,
  "x-sidereal.opacity": fraction,
  "x-sidereal.blur": wholePixels,
  "x-sidereal.border-width": wholePixels,
  "x-sidereal.size": wholePixels,
};

// The specification's own primitive groups.
const specGroups = ["colors", "rounded", "spacing"];

// Keys under x-sidereal that hold settings, not primitive tokens.
const extensionSettings = ["css-prefix", "semantic"];

function primitiveGroups(frontMatter: Record<string, unknown>): TokenGroup[] {
  const groups: TokenGroup[] = [];
  for (const path of specGroups) {
    const tokens = frontMatter[path];
    if (isMap(tokens)) groups.push({ path, tokens });
  }
  for (const [name, tokens] of Object.entries(extensionOf(frontMatter))) {
    if (extensionSettings.includes(name) || !isMap(tokens)) continue;
    groups.push({ path: `x-sidereal.${name}`, tokens });
  }
  return groups;
}

function extensionOf(
  frontMatter: Record<string, unknown>,
): Record<string, unknown> {
  const extension = frontMatter["x-sidereal"];
  return isMap(extension) ? extension : {};
}

function readIfExists(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

// Runs main() when Node runs this file directly. It sits last, so every
// constant above is initialized before main() reads it.
if (import.meta.main) {
  process.exitCode = main(process.argv.slice(2));
}
