name: CI Pipeline

on:
  push:
    branches:
      - main
      - v0.x
  pull_request:
    branches:
      - main
      - v0.x

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run type checking
        run: npm run check

      - name: Run unit tests
        run: npm run test

      - name: Build all packages
        run: npm run build

  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
